title: Enclave AI
email: "enclaveaiapp@gmail.com"
description: >-
  Your privacy-focused AI companion. Start your private AI journey today 
  with no sign-up required.
baseurl: ""
url: "https://enclaveai.app"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Social media and site info
author: Enclave AI
twitter:
  username: enclave_ai
  card: summary
logo: /assets/images/enclave-icon.png
favicon: /assets/images/favicon-32x32.png

# Include _pages directory and specific files
include:
  - _pages
  - google49916d0afa2ae3e9.html  # Add your verification file here

# Exclude development-specific files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - package.json
  - package-lock.json

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default" 