title: "Enclave AI - Secure, Offline AI Assistant"
short_title: "Enclave AI"
email: "enclaveaiapp@gmail.com"
description: "Privacy-focused AI chatbot for iOS and macOS that runs completely offline. Local LLM processing, secure conversations, and voice chat - all without internet. Your private AI assistant for iPhone, iPad, and Mac."
baseurl: ""
url: "https://enclaveai.app"

# App download link
app_store_url: "https://apps.apple.com/app/apple-store/id6476614556?pt=117876009&ct=enclave-website&mt=8"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Social media and site info
author: Enclave AI
twitter:
  username: enclave_ai
  card: summary
logo: /assets/images/enclave-icon.webp
favicon: /assets/images/favicon-32x32.png

# Include _pages directory and specific files
include:
  - _pages
  - google49916d0afa2ae3e9.html  # Add your verification file here

# Exclude development-specific files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - package.json
  - package-lock.json

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default" 